version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(message)s'
handlers:
  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: app.log
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    stream: ext://sys.stdout
loggers:
  my_application_logger:
    level: DEBUG
    handlers: [file_handler]
    propagate: no
  my_other_logger:
    level: INFO
    handlers: [console_handler]
    propagate: no
